version: '3.7'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8010:80"
    volumes:
      - ./app:/code/app
    depends_on:
      - bcra_db
    environment:
      - DATABASE_URL="postgresql://user_bcra:bcra1234@bcra_db/bcra_deudores"
      - VIRTUAL_HOST=bcra-api.libra-soft.com
      - LETSENCRYPT_EMAIL=levislibra@libra-soft.com
      - VIRTUAL_PORT=80
  bcra_db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_bcra
      POSTGRES_PASSWORD: bcra1234
      POSTGRES_DB: bcra_deudores
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:

networks:
  default:
    external:
      name: librasoft_default